/**
 * Lifecycle hook discovery and Codex hooks.json translation.
 *
 * Hook programs are standalone Bun TypeScript files. Explicit hook choices
 * are never dropped when a file is absent: the caller receives `missing`
 * metadata and owns the user-facing failure. Convention is optional only
 * when frontmatter did not force it.
 *
 * Generated commands are POSIX-shell strings because Codex executes hook
 * commands through the session shell. Both argv entries must remain quoted,
 * including runtimes and paths that contain spaces or single quotes.
 */

import { existsSync, readFileSync, realpathSync } from "node:fs";
import { basename, dirname, resolve, sep } from "node:path";
import { CommandError } from "./errors";
import type { AgentFrontmatter, HooksSpec, ToolAdapter } from "./types";

/**
 * Template marker anchoring static event discovery and surgical CLI edits.
 * Passive surfaces (explain, dry-run, the Workbench, `md hooks list`) must
 * NEVER execute a hooks file — discovery on those paths is text-only, so a
 * hooks file only runs when the flow itself runs.
 */
export const HANDLERS_OPEN_MARKER = "const handlers: Record<string, HookHandler> = {";

export const CANONICAL_HOOK_EVENTS = [
  "sessionStart",
  "userPromptSubmit",
  "preToolUse",
  "postToolUse",
  "permissionRequest",
  "preCompact",
  "postCompact",
  "subagentStart",
  "subagentStop",
  "stop",
  "sessionEnd",
] as const;

export type CanonicalHookEvent = (typeof CANONICAL_HOOK_EVENTS)[number];

export const CODEX_HOOK_EVENT_NAMES: Record<CanonicalHookEvent, string> = {
  sessionStart: "SessionStart",
  userPromptSubmit: "UserPromptSubmit",
  preToolUse: "PreToolUse",
  postToolUse: "PostToolUse",
  permissionRequest: "PermissionRequest",
  preCompact: "PreCompact",
  postCompact: "PostCompact",
  subagentStart: "SubagentStart",
  subagentStop: "SubagentStop",
  stop: "Stop",
  sessionEnd: "SessionEnd",
};

/**
 * Canonical → Claude Code settings event names. Every value below is in the
 * accepted-event registry of Claude Code 2.1.207 (verified via `claude
 * doctor` in docs/claude-hooks-probe-2026-07.md). In a print-mode run,
 * SessionStart, UserPromptSubmit, PreToolUse, PostToolUse, Stop, and
 * SessionEnd fire; the rest are registered but scenario-dependent.
 */
export const CLAUDE_HOOK_EVENT_NAMES: Record<CanonicalHookEvent, string> = {
  sessionStart: "SessionStart",
  userPromptSubmit: "UserPromptSubmit",
  preToolUse: "PreToolUse",
  postToolUse: "PostToolUse",
  permissionRequest: "PermissionRequest",
  preCompact: "PreCompact",
  postCompact: "PostCompact",
  subagentStart: "SubagentStart",
  subagentStop: "SubagentStop",
  stop: "Stop",
  sessionEnd: "SessionEnd",
};

export type ResolvedHooksFile =
  | { kind: "disabled" }
  | { kind: "none" }
  | {
      kind: "file";
      path: string;
      source: "convention" | "frontmatter" | "cli";
      missing: boolean;
      /**
       * Set when a frontmatter `_hooks:` path is rejected by policy: it
       * escapes the flow's directory, or the flow is remote (remote flows
       * may never select local hook programs). The caller must fail the run
       * with this message — never silently drop or silently run it.
       */
      rejected?: string;
    };

export interface CodexCommandHook {
  type: "command";
  command: string;
  timeout: number;
  statusMessage: string;
}

export interface CodexHooksJson {
  hooks: Record<string, Array<{ hooks: CodexCommandHook[] }>>;
}

const CANONICAL_HOOK_EVENT_SET = new Set<string>(CANONICAL_HOOK_EVENTS);
const LIST_EVENTS_FLAG = "--mdflow-list-events";
const LIST_EVENTS_CONTRACT_HINT =
  "The hooks file must be generated by `md hooks add` or support the " +
  `${LIST_EVENTS_FLAG} contract.`;

const HOOK_PROTOCOL_COMMENTS: Record<CanonicalHookEvent, string> = {
  sessionStart: "// return a string to inject startup context",
  userPromptSubmit:
    '// return a string to inject context; { decision: "block", reason } to reject the prompt',
  preToolUse:
    '// return { hookSpecificOutput: { permissionDecision: "deny" } } to deny',
  postToolUse: "// return void after observing the completed tool call",
  permissionRequest: "// return void to leave the permission request unchanged",
  preCompact: "// persist state before compaction; return void to continue",
  postCompact: "// inspect the compacted session; return void to continue",
  subagentStart: "// inspect the starting subagent; return void to continue",
  subagentStop:
    '// return { decision: "block", reason: "…" } to force the subagent turn to continue',
  stop: '// return { decision: "block", reason: "…" } to force the turn to continue',
  sessionEnd: "// observe final session state; return void",
};

/** Map any markdown flow name to its colocated TypeScript hook program. */
export function hooksFileForFlow(flowPath: string): string {
  return `${flowPath.replace(/\.md$/i, "")}.hooks.ts`;
}

/**
 * Resolve hook precedence without validating explicit file contents. Explicit
 * paths and forced convention return file results even when absent so the
 * run cannot silently lose declared behavior.
 */
export function resolveHooksFile(opts: {
  flowPath: string;
  frontmatterValue?: unknown;
  cliValue?: string;
  /** Remote/registry flows may never select local hook programs. */
  isRemote?: boolean;
}): ResolvedHooksFile {
  if (opts.cliValue !== undefined) {
    if (opts.cliValue === "false") return { kind: "disabled" };
    // The CLI value is typed by the invoking user — that is consent; no
    // containment applies.
    const path = resolve(opts.cliValue);
    return { kind: "file", path, source: "cli", missing: !existsSync(path) };
  }

  if (opts.frontmatterValue === false) return { kind: "disabled" };

  if (typeof opts.frontmatterValue === "string") {
    const flowDirectory = dirname(resolve(opts.flowPath));
    const path = resolve(flowDirectory, opts.frontmatterValue);
    const result: ResolvedHooksFile = {
      kind: "file",
      path,
      source: "frontmatter",
      missing: !existsSync(path),
    };
    // Containment: a flow file is data that anyone can author; its `_hooks:`
    // may only reach INTO the flow's own directory, never out of it. Hook
    // programs run on the host outside the engine sandbox, so an escaping
    // path would let a hostile flow execute an arbitrary local file. The
    // check is lexical first (works for missing targets), then CANONICAL
    // for existing targets — a symlink placed under the flow directory must
    // not smuggle in an outside program.
    const escapeMessage = () =>
      `_hooks path escapes the flow's directory (${opts.frontmatterValue} → ${path}). ` +
      `Move the hooks file under ${flowDirectory}${sep} or pass --_hooks <path> explicitly.`;
    if (opts.isRemote) {
      result.rejected =
        "remote flows cannot declare a _hooks path (hook programs run " +
        "unsandboxed on this machine); remove _hooks or run a local copy.";
    } else if (path !== flowDirectory && !path.startsWith(flowDirectory + sep)) {
      result.rejected = escapeMessage();
    } else if (!result.missing) {
      try {
        const canonicalTarget = realpathSync(path);
        const canonicalDir = realpathSync(flowDirectory);
        if (
          canonicalTarget !== canonicalDir &&
          !canonicalTarget.startsWith(canonicalDir + sep)
        ) {
          result.rejected = escapeMessage();
        }
      } catch {
        // realpath raced with deletion: treat as missing, never as allowed.
        result.missing = true;
      }
    }
    return result;
  }

  const path = hooksFileForFlow(opts.flowPath);
  const forceConvention = Boolean(opts.frontmatterValue);
  if (existsSync(path) || forceConvention) {
    return {
      kind: "file",
      path,
      source: "convention",
      missing: !existsSync(path),
    };
  }

  return { kind: "none" };
}

/**
 * Discover a hooks file's handled events WITHOUT executing it: parse the
 * template's `const handlers = { … }` map textually. This is the only
 * discovery mechanism allowed on passive surfaces (explain, dry-run, the
 * Workbench, `md hooks list`) — running user code during inspection would
 * grant a hooks file more reach than the flow body it accompanies.
 *
 * Files that keep the scaffolded shape (any file from `md hooks add`, or a
 * hand-written one preserving the marker and two-space `event:` keys) parse
 * here. Files that don't are handled per-surface: passive paths report
 * "not inspected", the real run path may fall back to executing
 * `--mdflow-list-events` because the flow is executing anyway.
 */
export function listHandledEventsStatic(
  hooksFile: string
): { ok: true; events: CanonicalHookEvent[] } | { ok: false; error: string } {
  let source: string;
  try {
    source = readFileSync(hooksFile, "utf8");
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return { ok: false, error: `Could not read hooks file "${hooksFile}": ${message}` };
  }

  const open = source.indexOf(HANDLERS_OPEN_MARKER);
  if (open === -1) {
    return {
      ok: false,
      error:
        `Hooks file "${hooksFile}" has no statically readable handlers map ` +
        `(missing \`${HANDLERS_OPEN_MARKER}\`). Regenerate it with ` +
        "`md hooks add`, or keep the template's handlers shape so mdflow " +
        "can inspect it without executing it.",
    };
  }
  const close = source.indexOf("\n};", open);
  if (close === -1) {
    return {
      ok: false,
      error: `Hooks file "${hooksFile}" has an unterminated handlers map; cannot inspect statically.`,
    };
  }

  const body = source.slice(open + HANDLERS_OPEN_MARKER.length, close);
  const events: CanonicalHookEvent[] = [];
  for (const match of body.matchAll(/^  ([A-Za-z]+):/gm)) {
    const name = match[1]!;
    if (!CANONICAL_HOOK_EVENT_SET.has(name)) {
      return {
        ok: false,
        error:
          `Unknown hook event "${name}" in "${hooksFile}". ` +
          `Valid events: ${CANONICAL_HOOK_EVENTS.join(", ")}.`,
      };
    }
    if (!events.includes(name as CanonicalHookEvent)) {
      events.push(name as CanonicalHookEvent);
    }
  }

  if (events.length === 0) {
    return { ok: false, error: `hooks file handles no events: "${hooksFile}".` };
  }
  return { ok: true, events };
}

/**
 * Query a standalone hooks file for the canonical events it implements by
 * EXECUTING it with `--mdflow-list-events`. Reserved for the real run path
 * as a fallback when static parsing fails — the flow is about to execute,
 * so running its declared hook program carries no additional consent.
 * Passive surfaces must use listHandledEventsStatic instead.
 */
export async function listHandledEvents(
  hooksFile: string,
  opts: { timeoutMs?: number; runtime?: string } = {}
): Promise<
  | { ok: true; events: CanonicalHookEvent[] }
  | { ok: false; error: string }
> {
  const runtime = opts.runtime ?? process.execPath;
  const timeoutMs = opts.timeoutMs ?? 5_000;
  let proc: ReturnType<typeof Bun.spawn>;

  try {
    proc = Bun.spawn([runtime, hooksFile, LIST_EVENTS_FLAG], {
      stdin: "ignore",
      stdout: "pipe",
      stderr: "pipe",
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return {
      ok: false,
      error: `Could not start hooks file "${hooksFile}": ${message}. ${LIST_EVENTS_CONTRACT_HINT}`,
    };
  }

  let timedOut = false;
  const timer = setTimeout(() => {
    if (proc.exitCode !== null) return;
    timedOut = true;
    try {
      proc.kill("SIGKILL");
    } catch {}
  }, timeoutMs);

  let stdout: string;
  let stderr: string;
  let exitCode: number;
  try {
    [stdout, stderr, exitCode] = await Promise.all([
      new Response(proc.stdout as ReadableStream<Uint8Array>).text(),
      new Response(proc.stderr as ReadableStream<Uint8Array>).text(),
      proc.exited,
    ]);
  } catch (error) {
    try {
      if (proc.exitCode === null) proc.kill("SIGKILL");
    } catch {}
    const message = error instanceof Error ? error.message : String(error);
    return {
      ok: false,
      error: `Could not read hooks file "${hooksFile}": ${message}. ${LIST_EVENTS_CONTRACT_HINT}`,
    };
  } finally {
    clearTimeout(timer);
  }

  if (timedOut) {
    return {
      ok: false,
      error: `Hooks file "${hooksFile}" timed out after ${timeoutMs}ms. ${LIST_EVENTS_CONTRACT_HINT}`,
    };
  }

  if (exitCode !== 0) {
    const detail = stderr.trim();
    return {
      ok: false,
      error:
        `Hooks file "${hooksFile}" exited with code ${exitCode}` +
        `${detail ? `: ${detail}` : "."} ${LIST_EVENTS_CONTRACT_HINT}`,
    };
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(stdout);
  } catch {
    return {
      ok: false,
      error:
        `Hooks file "${hooksFile}" did not print a JSON array of events. ` +
        LIST_EVENTS_CONTRACT_HINT,
    };
  }

  if (!Array.isArray(parsed)) {
    return {
      ok: false,
      error:
        `Hooks file "${hooksFile}" did not print a JSON array of events. ` +
        LIST_EVENTS_CONTRACT_HINT,
    };
  }

  if (parsed.length === 0) {
    return {
      ok: false,
      error: `hooks file handles no events: "${hooksFile}". ${LIST_EVENTS_CONTRACT_HINT}`,
    };
  }

  for (const event of parsed) {
    if (typeof event !== "string" || !CANONICAL_HOOK_EVENT_SET.has(event)) {
      return {
        ok: false,
        error:
          `Unknown hook event ${JSON.stringify(event)} from "${hooksFile}". ` +
          `Valid events: ${CANONICAL_HOOK_EVENTS.join(", ")}.`,
      };
    }
  }

  return { ok: true, events: parsed as CanonicalHookEvent[] };
}

function quotePosixShellArg(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

/**
 * TOML basic-string escape for inline `-c` override values. Codex parses the
 * override as TOML, so `"` and `\` in paths must survive; control characters
 * are escaped for completeness.
 */
function tomlEscape(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
}

/**
 * Serialize a codex hooks config as ONE inline `-c` override value:
 *   hooks={SessionStart=[{hooks=[{type="command",command="…",timeout=60,…}]}]}
 *
 * Verified against codex-cli 0.144.1: the dotted/inline `-c` forms load hook
 * definitions with NO hooks.json on disk, aggregate with (never clobber) the
 * user's ambient hooks, and survive --ignore-user-config and --ephemeral.
 * Event keys MUST be PascalCase — snake_case silently registers nothing.
 * The nesting (event → group list → group.hooks list) is mandatory.
 */
export function buildCodexHooksOverride(config: CodexHooksJson): string {
  const eventEntries = Object.entries(config.hooks).map(([event, groups]) => {
    const groupEntries = groups.map((group) => {
      const commandEntries = group.hooks.map(
        (hook) =>
          `{type="${tomlEscape(hook.type)}",command="${tomlEscape(hook.command)}",` +
          `timeout=${hook.timeout},statusMessage="${tomlEscape(hook.statusMessage)}"}`
      );
      return `{hooks=[${commandEntries.join(",")}]}`;
    });
    return `${event}=[${groupEntries.join(",")}]`;
  });
  return `hooks={${eventEntries.join(",")}}`;
}

/** Translate canonical events into Codex's native hooks.json command shape. */
export function buildCodexHooksConfig(opts: {
  hooksFile: string;
  events: CanonicalHookEvent[];
  runtime?: string;
  timeoutSeconds?: number;
}): CodexHooksJson {
  const runtime = opts.runtime ?? process.execPath;
  const command =
    `${quotePosixShellArg(runtime)} ` +
    quotePosixShellArg(resolve(opts.hooksFile));
  const hooks: CodexHooksJson["hooks"] = {};

  for (const event of opts.events) {
    hooks[CODEX_HOOK_EVENT_NAMES[event]] = [
      {
        hooks: [
          {
            type: "command",
            command,
            timeout: opts.timeoutSeconds ?? 60,
            statusMessage: `mdflow hook: ${event}`,
          },
        ],
      },
    ];
  }

  return { hooks };
}

export interface ClaudeHooksSettings {
  hooks: Record<
    string,
    Array<{ matcher: string; hooks: Array<{ type: "command"; command: string; timeout: number }> }>
  >;
}

/**
 * Build Claude Code's native settings-hooks object for the given events.
 * Shape verified on Claude Code 2.1.207: `hooks -> Event -> [{matcher, hooks:
 * [{type, command, timeout}]}]`. `matcher: ""` matches every occurrence.
 * The command runs through a shell, so runtime + path are shell-quoted; the
 * whole object is later JSON-serialized into one `--settings` argv value
 * (no shell involved at that layer, so JSON escaping is all that remains).
 */
export function buildClaudeHooksSettings(opts: {
  hooksFile: string;
  events: CanonicalHookEvent[];
  runtime?: string;
  timeoutSeconds?: number;
}): ClaudeHooksSettings {
  const runtime = opts.runtime ?? process.execPath;
  const command =
    `${quotePosixShellArg(runtime)} ` + quotePosixShellArg(resolve(opts.hooksFile));
  const hooks: ClaudeHooksSettings["hooks"] = {};
  for (const event of opts.events) {
    hooks[CLAUDE_HOOK_EVENT_NAMES[event]] = [
      {
        matcher: "",
        hooks: [{ type: "command", command, timeout: opts.timeoutSeconds ?? 60 }],
      },
    ];
  }
  return { hooks };
}

/** Serialize claude settings-hooks as one inline `--settings` argv value. */
export function buildClaudeHooksSettingsValue(config: ClaudeHooksSettings): string {
  return JSON.stringify(config);
}

/** Render an inert, self-contained Bun hook program for the requested events. */
export function renderHooksTemplate(events: CanonicalHookEvent[]): string {
  const requestedEvents = [...new Set(events)];
  const lines = [
    "#!/usr/bin/env bun",
    "",
    "type HookPayload = { session_id: string; transcript_path: string; cwd: string; hook_event_name: string; model?: string; turn_id?: string; [key: string]: unknown };",
    "type HookResult = void | string | Record<string, unknown>;",
    "type HookHandler = (payload: HookPayload) => HookResult | Promise<HookResult>;",
    "",
    "const handlers: Record<string, HookHandler> = {",
  ];

  for (const event of requestedEvents) {
    lines.push(`  ${event}: async (_payload: HookPayload): Promise<HookResult> => {`);
    lines.push(`    ${HOOK_PROTOCOL_COMMENTS[event]}`);
    lines.push("  },");
  }

  lines.push(
    "};",
    "",
    "// Guard events decide whether an action is allowed. If their handler",
    "// THROWS, failing open would let the guarded action through — so mdflow",
    "// emits the engine's block/deny response instead. Observational events",
    "// (sessionStart, postToolUse, stop, …) fail open: a crash there must not",
    "// wedge the run (blocking Stop on error would loop forever).",
    "const FAIL_CLOSED: Record<string, (reason: string) => Record<string, unknown>> = {",
    '  userPromptSubmit: (reason) => ({ decision: "block", reason }),',
    '  preToolUse: (reason) => ({ hookSpecificOutput: { hookEventName: "PreToolUse", permissionDecision: "deny", permissionDecisionReason: reason } }),',
    '  permissionRequest: (reason) => ({ hookSpecificOutput: { hookEventName: "PermissionRequest", permissionDecision: "deny", permissionDecisionReason: reason } }),',
    "};",
    "",
    "async function main(): Promise<void> {",
    `  if (process.argv.includes("${LIST_EVENTS_FLAG}")) {`,
    "    process.stdout.write(JSON.stringify(Object.keys(handlers)));",
    "    return;",
    "  }",
    "",
    "  let payload: HookPayload;",
    "  try {",
    "    const parsed: unknown = JSON.parse(await Bun.stdin.text());",
    '    if (parsed === null || typeof parsed !== "object") return;',
    "    payload = parsed as HookPayload;",
    "  } catch {",
    "    return;",
    "  }",
    "",
    '  if (typeof payload.hook_event_name !== "string") return;',
    "  const eventName = payload.hook_event_name",
    "    .replace(/_([a-zA-Z])/g, (_, letter: string) => letter.toUpperCase())",
    "    .replace(/^[A-Z]/, (letter) => letter.toLowerCase());",
    "  const handler = handlers[eventName];",
    "  if (!handler) return;",
    "",
    "  try {",
    "    const result = await handler(payload);",
    '    if (typeof result === "string") {',
    "      process.stdout.write(result);",
    "    } else if (result !== undefined) {",
    "      process.stdout.write(JSON.stringify(result));",
    "    }",
    "  } catch (error) {",
    "    const message = error instanceof Error ? error.message : String(error);",
    "    console.error(`mdflow hook failed: ${message}`);",
    "    const failClosed = FAIL_CLOSED[eventName];",
    "    if (failClosed) {",
    "      process.stdout.write(JSON.stringify(failClosed(`hook error: ${message}`)));",
    "      process.exit(0);",
    "    }",
    "  }",
    "}",
    "",
    "await main();",
    ""
  );

  return lines.join("\n");
}

/** Format hook discovery for stderr; the caller owns terminal styling. */
export function formatHooksStderrLine(
  hooksFile: string,
  events: CanonicalHookEvent[]
): string {
  return `hooks: ${basename(hooksFile)} (${events.join(", ")})`;
}

export interface AppliedHooks {
  frontmatter: AgentFrontmatter;
  /** Dim disclosures to surface on stderr (e.g. claude isolation tradeoff). */
  warnings: string[];
}

/**
 * Apply a discovered hooks file via the engine adapter. Same contract as
 * applySystemPromptToFrontmatter: engines with no applyHooks translation FAIL
 * the run — a flow whose hooks file exists but silently never fires is a
 * different flow. `_hooks: false` is the explicit opt-out.
 */
export function applyHooksToFrontmatter(
  adapter: ToolAdapter,
  command: string,
  frontmatter: AgentFrontmatter,
  spec: HooksSpec
): AppliedHooks {
  if (!adapter.applyHooks) {
    throw new CommandError(
      `${command} has no verified lifecycle-hook mechanism; a hooks file ` +
        `exists for this flow (${basename(spec.hooksFile)}) but cannot run. ` +
        `Switch the flow to an engine with hook support (codex, claude), or ` +
        `set \`_hooks: false\` to run without hooks.`,
      { errorCode: "HOOKS_UNSUPPORTED", context: { command, hooksFile: spec.hooksFile } }
    );
  }

  const translation = adapter.applyHooks(spec);

  // Ownership conflict: if the flow itself supplies a key the translation
  // owns (e.g. claude `settings:`), fail rather than let argv order decide.
  for (const key of translation.exclusiveKeys ?? []) {
    if (frontmatter[key] !== undefined) {
      throw new CommandError(
        `${command} hooks own the \`${key}\` setting, but this flow already ` +
          `sets \`${key}\`. Remove the flow's \`${key}\` or set \`_hooks: false\`.`,
        { errorCode: "HOOKS_UNSUPPORTED", context: { command, key } }
      );
    }
  }

  const result: AgentFrontmatter = { ...frontmatter };
  delete result._hooks;

  for (const [key, value] of Object.entries(translation.frontmatter ?? {})) {
    const existing = result[key];
    if (Array.isArray(value)) {
      const base = existing === undefined ? [] : Array.isArray(existing) ? existing : [existing];
      result[key] = [...base, ...value];
    } else {
      result[key] = value;
    }
  }

  if (translation.env && Object.keys(translation.env).length > 0) {
    const existingEnv =
      typeof result._env === "object" && result._env !== null && !Array.isArray(result._env)
        ? (result._env as Record<string, string>)
        : {};
    result._env = { ...existingEnv, ...translation.env };
  }

  return { frontmatter: result, warnings: translation.warnings ?? [] };
}
